version: '3.8'

services:
  mysql-ts-api:
    image: mysql-ts-api
    build: .
    environment: 
      FRONT_PORT: 8080
      BACK_PORT: 3000
    volumes:
      - .:/run
      - nodemodules:/run/node_modules
    ports:
      - 3000:3000
      - 8080:8080
volumes:
  nodemodules: {}
